import { PrismaClient } from "@prisma/client";
import { scoreOpportunity } from "../lib/booking-lifecycle";
const prisma = new PrismaClient();
const date = (days: number, hour = 19): Date => { const d = new Date(); d.setDate(d.getDate() + days); d.setHours(hour, 0, 0, 0); return d; };
async function main(): Promise<void> {
  await prisma.message.deleteMany(); await prisma.conversation.deleteMany(); await prisma.payment.deleteMany(); await prisma.task.deleteMany(); await prisma.calendarEvent.deleteMany(); await prisma.booking.deleteMany(); await prisma.opportunity.deleteMany(); await prisma.contact.deleteMany(); await prisma.venue.deleteMany(); await prisma.artist.deleteMany(); await prisma.integration.deleteMany();
  const artist = await prisma.artist.create({ data: { name: "George Grissom", homeCity: "Seattle", homeState: "WA" } });
  const fixtures = [
    { name: "[Sample] Example Pub — Sample Data", city: "Edmonds", type: "pub", status: "READY_FOR_OUTREACH", rel: "COLD_LEAD", suitability: 88, source: "venue_website", contact: "Jordan Sample", role: "Music Booker" },
    { name: "[Sample] Harborlight Winery — Sample Data", city: "Woodinville", type: "winery", status: "WAITING_FOR_REPLY", rel: "RECENTLY_CONTACTED", suitability: 92, source: "manual", contact: "Casey Demo", role: "Events Manager" },
    { name: "[Sample] Cedar Grove Community — Sample Data", city: "Bellevue", type: "retirement_community", status: "CONFIRMED", rel: "REPEAT_VENUE", suitability: 82, source: "referral", contact: "Morgan Example", role: "Activities Director" },
    { name: "[Sample] Summit Hotel Lounge — Sample Data", city: "Seattle", type: "hotel", status: "DATE_PROPOSED", rel: "KNOWN_CONTACT", suitability: 76, source: "gmail", contact: "Riley Placeholder", role: "Food & Beverage Manager" },
    { name: "[Sample] Pine & Pour Brewery — Sample Data", city: "Kirkland", type: "brewery", status: "LEAD", rel: "COLD_LEAD", suitability: 70, source: "venue_website", contact: "Alex Sample", role: "General Manager" }
  ];
  for (let index = 0; index < fixtures.length; index++) {
    const row = fixtures[index]; const venue = await prisma.venue.create({ data: { name: row.name, address: `${100 + index} Example Avenue`, city: row.city, state: "WA", zip: "98000", venueType: row.type, musicStyleTags: "acoustic, singer-songwriter", soloAcousticSuitability: row.suitability, typicalShowSchedule: "Sample schedule: evenings", paProvided: index % 2 === 0, relationshipStatus: row.rel, timesPerformed: row.rel === "REPEAT_VENUE" ? 2 : 0, discoveredVia: "Sample seed data only", notes: "Fictional example data for Bookt development; not a record of real venue history." } });
    const contact = await prisma.contact.create({ data: { venueId: venue.id, name: row.contact, role: row.role, email: `contact${index + 1}@example.test`, phone: "206-555-01" + String(index).padStart(2, "0"), preferredChannel: "email", notes: "Fictional sample contact." } });
    const scoring = scoreOpportunity({ suitability: row.suitability, relationshipStatus: row.rel, hasContact: true, proposedDates: index > 2 ? JSON.stringify([date(7 + index)]) : null });
    const opportunity = await prisma.opportunity.create({ data: { venueId: venue.id, contactId: contact.id, artistId: artist.id, status: row.status, priorityScore: scoring.score, scoreReasons: scoring.reasons, sourceType: row.source, proposedDates: index > 2 ? JSON.stringify([date(7 + index).toISOString()]) : null, notes: "Fictional sample opportunity; verify all details before any real outreach." } });
    if (index < 2) { const convo = await prisma.conversation.create({ data: { opportunityId: opportunity.id, venueId: venue.id, channel: "email", needsReply: index === 1, lastMessageAt: date(-2) } }); await prisma.message.create({ data: { conversationId: convo.id, direction: "outbound", channel: "email", subject: "Sample outreach draft", body: "This is fictional development data.", draftStatus: index === 0 ? "draft" : "approved", sentAt: null } }); }
    if (["CONFIRMED", "DATE_PROPOSED"].includes(row.status)) { const booking = await prisma.booking.create({ data: { opportunityId: opportunity.id, artistId: artist.id, venueId: venue.id, contactId: contact.id, status: row.status, performanceDate: date(index === 2 ? 4 : 12), showStart: date(index === 2 ? 4 : 12), showEnd: date(index === 2 ? 4 : 12, 21), paymentAmountCents: 25000, guaranteeCents: 25000, paymentMethod: "Sample invoice", paymentTiming: "Due after performance", venueAddressSnapshot: `${venue.address}, ${venue.city}, WA`, contactPhoneSnapshot: contact.phone, notes: "Fictional sample booking." } }); await prisma.calendarEvent.create({ data: { bookingId: booking.id, startsAt: date(index === 2 ? 4 : 12), endsAt: date(index === 2 ? 4 : 12, 21), kind: "performance", title: `Sample performance: ${venue.name}`, notes: "Local-only sample event." } }); await prisma.payment.create({ data: { bookingId: booking.id, amountCents: 25000, status: index === 2 ? "pending" : "paid", dueDate: date(index === 2 ? 4 : 12), paidAt: index === 2 ? null : date(-1) } }); await prisma.task.create({ data: { bookingId: booking.id, relatedType: "booking", relatedId: booking.id, title: index === 2 ? "Confirm sample load-in details" : "Send sample thank-you", dueAt: date(index === 2 ? 2 : -1), kind: index === 2 ? "logistics" : "thank_you" } }); }
    else await prisma.task.create({ data: { relatedType: "opportunity", relatedId: opportunity.id, title: `Follow up on ${venue.name}`, dueAt: index === 1 ? date(-1) : date(3), kind: "follow_up" } });
  }
  await prisma.calendarEvent.create({ data: { startsAt: date(10), endsAt: date(10, 21), kind: "personal", title: "[Sample] Personal conflict", notes: "Fictional blocked time to demonstrate conflict checks." } });
  await prisma.integration.createMany({ data: ["google_calendar", "gmail", "calendly", "twilio", "sendblue"].map((provider) => ({ provider, status: "not_configured" })) });
}
main().then(() => prisma.$disconnect()).catch(async (error: unknown) => { console.error(error); await prisma.$disconnect(); process.exit(1); });
