import { prisma } from "@/lib/prisma";
import { DEAL_STATUSES, SOURCE_TYPES, label } from "@/lib/constants";
import { PageHeader } from "@/components/shell";
import { createOpportunity } from "../actions";

export default async function NewOpportunityPage({ searchParams }: { searchParams: Promise<{ error?: string; venueId?: string }> }): Promise<React.ReactNode> {
  const { error, venueId } = await searchParams;
  const venues = await prisma.venue.findMany({ orderBy: { name: "asc" }, include: { contacts: true } });
  return <><PageHeader title="Add an opportunity" description="Turn a venue relationship into a tracked opportunity with a priority score."/>{error && <p role="alert" className="mb-5 rounded-lg bg-rose-100 p-3 text-sm text-rose-900">{error}</p>}{venues.length === 0 ? <p className="rounded-xl border border-stone-300 bg-white p-5 text-sm text-stone-600">Add a venue first before creating an opportunity.</p> : <form action={createOpportunity} className="max-w-2xl space-y-4 rounded-xl border border-stone-300 bg-white p-5"><label className="block text-sm font-medium">Venue<select name="venueId" required defaultValue={venueId ?? ""} className="mt-1 w-full rounded-lg border border-stone-300 p-2 text-sm"><option value="" disabled>Choose a venue</option>{venues.map((venue) => <option key={venue.id} value={venue.id}>{venue.name}</option>)}</select></label><label className="block text-sm font-medium">Contact (optional)<select name="contactId" defaultValue="" className="mt-1 w-full rounded-lg border border-stone-300 p-2 text-sm"><option value="">No contact yet</option>{venues.flatMap((venue) => venue.contacts.map((contact) => <option key={contact.id} value={contact.id}>{venue.name} — {contact.name}</option>))}</select></label><label className="block text-sm font-medium">Discovered via<select name="sourceType" required defaultValue="manual" className="mt-1 w-full rounded-lg border border-stone-300 p-2 text-sm">{SOURCE_TYPES.map((source) => <option key={source} value={source}>{label(source)}</option>)}</select></label><label className="block text-sm font-medium">Starting status<select name="status" defaultValue="LEAD" className="mt-1 w-full rounded-lg border border-stone-300 p-2 text-sm">{DEAL_STATUSES.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></label><label className="block text-sm font-medium">Proposed date (optional)<input name="proposedDate" type="datetime-local" className="mt-1 w-full rounded-lg border border-stone-300 p-2 text-sm"/></label><label className="block text-sm font-medium">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded-lg border border-stone-300 p-2 text-sm"/></label><button className="rounded-lg bg-teal-800 px-4 py-2 text-sm font-semibold text-white">Save opportunity</button></form>}</>;
}
